### ISSUE TITLE
Upgrade: Configuration.ini files overwrite existing configuration

### ISSUE THREAD

**Issue by jeffnm** [wc-library/Coral#11]
The configuration.ini files were included in a commit to the upgrader. This could result in overwriting existing configuration.ini files when upgrading since one common approach is to simply copy the new files over the old. Depending on permissions, this may get blocked by default, but we should only include configuration_sample.ini files in the repository itself, not the actual configuration.ini.

**Comment by jcuenod** [comment]
oops, thanks, I'll fix that.

**Comment by jcuenod** [comment]
Are you sure about this? Which one(s) are you seeing?

**Comment by jeffnm** [comment]
I had all of them. Now that I think about it, it's possible I had generated them when testing the installer and didn't delete them when I checked out the upgrader. I'll check tomorrow to be sure.

**Comment by jeffnm** [comment]
Yeah, this was my mistake. I had config files from testing the installer and when I checked out the updater branch they obviously didn't get overwritten since they are in the gitignore. Sorry about that!
