### ISSUE TITLE
update_NEXT.sql files need to be changed to 2.0.0 files and verified

### ISSUE THREAD

**Issue by jeffnm** [wc-library/Coral#12]
The licensing module's update_NEXT.sql file was not renamed yet, and it has a strange ALTER TABLE query that tries to change a column SFXProvider that does not exist in the table SFXProvider.

**Comment by jeffnm** [comment]
OK, I checked the history of the update_NEXT.sql file and it definitely has issues that need to be addressed. I'm not sure that any of the changes in it are actually needed for the licensing module. It seems that only changes made to install.sql were removing the _DATABASE_NAME_ and that does not require an update.sql file.

It seems to me we should get rid of the licensing update_NEXT.sql file and move on with the other modules that do have changes.

**Comment by jcuenod** [comment]
Is this something you would like me to do?
