### ISSUE TITLE
Update Prompt is hard to notice

### ISSUE THREAD

**Issue by jeffnm** [wc-library/Coral#13]
The update prompt is too hard to notice, particularly since it will only appear if the administrator has already replaced the code with a newer version, and thus is expecting to be prompted to run the SQL updates.

**Comment by jcuenod** [comment]
To be honest I just wanted to put it somewhere unobtrusive. I agree it's hard to notice though (I also didn't want it to be triggered by some enthusiastic student worker). But I'll file another issue in that regard. What were you thinking it should look like and where should it be? Is this not a question for the design people?

**Comment by jeffnm** [comment]
What design people? ;)

I'm just concerned someone will think they've completed the update before they actually have.

**Comment by jcuenod** [comment]
Whoever did the nice new css?
Ahh, yes, good point.
I'm going to suggest closing this issue in favour of #14 then though...
