### ISSUE TITLE
Getting out of upgrade mode / force upgrade?

### ISSUE THREAD

**Issue by jcuenod** [wc-library/Coral#14]
Currently I don't think there's a way to escape "upgrade mode" after you've initiated it. Obviously we don't want people leaving half way through but we also don't want them clicking upgrade, realising they don't know the admin password for the db and then not being able to get back to the index page until the session expires (cf. #13)... or do we?

Maybe we want to force an upgrade if one is available because otherwise the code has been updated and the necessary updates wont have been run on its behalf...

**Comment by jeffnm** [comment]
That's what I think. If new code is in place but the required database changes haven't been run, we want to have those charges made. I think it's safe to assume end users aren't copying new code over their production instances, so expecting to run the update as soon as it is "available" makes sense to me. 

This may be a conversation we need to have with the steering committee to be sure though.

**Comment by jcuenod** [comment]
Okay so the index page redirects to the upgrade page if there is one.
It makes a lot more sense to me to do it this way round.
I will do that.
And to think I spent time injecting that silly link.

**Comment by jcuenod** [comment]
Okay, I'm closing this issue now; the installer will immediately redirect to run the upgrade without user initiation. You have to run the upgrader once the new code is in so this is fine.
