### ISSUE TITLE
Add a note about updating to default install page

### ISSUE THREAD

**Issue by jeffnm** [wc-library/Coral#15]
The default install page says it can't tell if CORAL is installed or not. In order to proceed during an upgrade the user must choose the option that says CORAL is already installed, but that's not obvious when a user thinks they need to be installing the new version. It would be good to mention that in one of the notes on the page.

**Comment by jcuenod** [comment]
So how about, "Coral is already installed, help me run the upgrade"?

**Comment by jeffnm** [comment]
Or, "CORAL is already installed, help me update or repair my installation"? Since if it is already installed but it's missing its common config file it needs to generate that without really updating anything.

**Comment by jcuenod** [comment]
Fixed in 0a4f1d0
