### ISSUE TITLE
Missing upgrade sql does not have retry button

### ISSUE THREAD

**Issue by jeffnm** [wc-library/Coral#16]
> Could not open sql file: licensing/install/protected/update_2.0.0.sql.
> If this file does not exist you must download new install files.

But no retry button like the other pages (this might be intentional because it seems they got a bad installer)

**Comment by jcuenod** [comment]
Correct - it doesn't seem like something that needs a retry...

**Comment by jeffnm** [comment]
OK. I'll close this issue.
