### ISSUE TITLE
No default database hostname

### ISSUE THREAD

**Issue by jeffnm** [wc-library/Coral#2]
If a user does not enter a database hostname during install, there is no default and no warning. It should default to localhost if nothing is entered since that is the most common case.

**Comment by jcuenod** [comment]
I think it would be better to force the user to enter something and give localhost as a default. Irrespective, will do.

**Comment by jeffnm** [comment]
> I think it would be better to force the user to enter something and give localhost as a default. 

I agree.

**Comment by jcuenod** [comment]
Should be fixed in the latest pull request (https://github.com/wc-library/Coral/pull/4)
