### ISSUE TITLE
Updater prompts for 777 even without have_read_write_access_to_config dependency

### ISSUE THREAD

**Issue by jeffnm** [wc-library/Coral#22]
I may be misunderstanding how this works, but if I leave have_read_write_access_to_config out of the dependency array for a case in the $version switch, shouldn't I be able to run the upgrade without being prompted to change permissions on my config files?

**Comment by jcuenod** [comment]
Yes you should be able to. This does sound like a bug but I'd like to see your code...

**Comment by jeffnm** [comment]
This is one of the modules that it occurred on: https://github.com/wc-library/Coral/blob/unified_installer/auth/install/auth.php

The upgrader wanted 777 permission to it and all the other module configuration.ini files that had SQL changes. 

It worked well enough that I went ahead and pushed it to the unified_installer branch here, but I wasn't sure why it wanted that permission. I've probably missed something obvious.
