### ISSUE TITLE
error messages for upgrades from old versions of modules are not clear

### ISSUE THREAD

**Issue by jeffnm** [wc-library/Coral#28]
For example, starting with Auth 1.0 instead of 1.1.1 results in this message:
`"Dependency for 'Incremental Upgrade' not found: auth"` 
which an average person would expect means that the module isn't there at all. Looking at the directory structure and seeing an auth folder will leave them confused. 

Can we find a more clear way of expressing this situation?

**Comment by jcuenod** [comment]
See https://github.com/jcuenod/Coral/commit/65d723b42ef71db8f823e2bbb7da5b83e3f9fdaf

**Comment by jeffnm** [comment]
That's good, thanks. I'm going to leave this issue open until that gets merged into coral-erm/coral:master though.
