### ISSUE TITLE
update /common/configuration_sample.ini

### ISSUE THREAD

**Issue by jeffnm** [wc-library/Coral#29]
`/common/configuration_sample.ini` doesn't seem to reflect what ends up in `/common/configuration.ini` 

Let's update it so that if someone were to attempt a manual installation of 2.0 that they would have a correct sample file to start with.

**Comment by jcuenod** [comment]
See jcuenod/Coral@3910ab1ec77b7376fd4af8f0ffb222a465c663c2
Actually, I'd appreciate review of this sample file - I'm not sure if that's what you are looking for...
