### ISSUE TITLE
Weird "can't tell if CORAL is installed" redirects

### ISSUE THREAD

**Issue by jeffnm** [wc-library/Coral#3]
During two different test installations I had a step redirect me to the page that asks the user if CORAL is already installed. 

The first time was when entering the CORAL admin user. The second time was when clicking retry during the directory permissions need to be 777 page. Both times I clicked Install CORAL and it returned to the step I was on previously. 

I'm not sure yet what is causing it or how to reproduce it, but am logging it here in case we continue to see it.

**Comment by jcuenod** [comment]
Hmm, agreed that's bizarre. The user response should be stored in a session variable.

**Comment by jeffnm** [comment]
It just occurred again for me on the second time I clicked "try again" during the chmod 777 permissions check. All the permissions were resolved, so it should have proceeded, instead it went to the "Can't tell if it's installed" page. Clicking "Install" resumes the process at the correct point (Have default user).

**Comment by jcuenod** [comment]
Strange, thanks for reporting, I'll experiment... (is this higher priority
than the updater?)

**Comment by jeffnm** [comment]
No. It's not breaking anything, yet.

**Comment by jcuenod** [comment]
I think this may have been fixed by reworking the `test_if_installed` code. I remember realising a logical flaw there but I have no idea what it was and it was a long time ago. I just noticed you were cleaning up these issues. Post if this happens again and in what branch it happened (and what revision).

**Comment by jeffnm** [comment]
Good to know. I've not tried it recently, but I'll let you know if it shows up again.

**Comment by jeffnm** [comment]
I've not seen this during the upgrades at all.
