### ISSUE TITLE
Location redirect in /install/index.php doesn't work on Windows

### ISSUE THREAD

**Issue by connordelacruz** [wc-library/Coral#5]
In /install/index.php, the assignment for $location gives it a string to a filepath rather than a valid URL (e.g. C:\xampp\htdocs\Coral where C:\xampp\htdocs is the root of localhost).

**Comment by connordelacruz** [comment]
The page was redirecting indefinitely because SCRIPT_FILENAME used forward slashes and **DIR** used backslashes, so it was always running the block that redirected it to $location (which wasn't getting changed because of the use of backslashes).

**Comment by jcuenod** [comment]
Thanks for the fix
