### ISSUE TITLE
Can't Use Existing Tables on Auth with Same Admin User

### ISSUE THREAD

**Issue by jcuenod** [wc-library/Coral#6]
(on `unified_installer` branch - actually this happened while I was on my own `upgrades` branch but I suspect it carries over) I think if you use the same username and choose to use existing tables with auth, it will fail because it can't write a duplicate entry.

```
Fatal error:  Uncaught exception 'RuntimeException' with message 'There was a problem with the database: Duplicate entry 'coral' for key 'PRIMARY'' in /srv/http/Coral/common/DBService.php:97
Stack trace:
#0 /srv/http/Coral/auth/install/auth.php(249): DBService->processQuery('INSERT INTO `Us...')
#1 [internal function]: {closure}(Array)
#2 /srv/http/Coral/install/installer.php(224): call_user_func(Object(Closure), Array)
#3 /srv/http/Coral/install/installer.php(214): Installer->actuallyRunTest('auth', Array)
#4 /srv/http/Coral/install/installer.php(208): Installer->runTestForResult('auth', Array)
#5 /srv/http/Coral/install/installer.php(208): Installer->runTestForResult('modules_to_use_...', Array)
#6 /srv/http/Coral/install/index.php(104): Installer->runTestForResult('set_installed_v...')
#7 /srv/http/Coral/install/index.php(158): run_loop('INSTALL')
#8 /srv/http/Coral/install/index.php(211): do_install()
#9 /srv/http/Coral/index.php(4): require_once('/srv/http/Coral...')
#10 {main}
  thrown in /srv/http/Coral/common/DBService.php on line 97
```

note that the key was "coral" so I think this is an issue with the default admin user.
The solution is probably to drop existing rows that match the user id but maybe that undermines the point of using existing tables... I'm not sure what to do here (and I don't think it's completely an edge case - it's not unlikely for someone to want to use existing tables and retain their username and password stuff).

**Comment by jeffnm** [comment]
One idea would be can you check if the admin user already exists? If so, check that it's an admin, and if not update it to be an admin? 

If someone is upgrading, you shouldn't need to be asking them for an admin user as they already have the user table populated and we don't want to mess with that unless the user data model is changing. 

If someone is doing  a fresh install, but keeping an existing database for one of the modules, that is likely going to require them to edit their configuration files manually to point it at the right database. Typically, such a situation would mean they needed to run the update code anyway.
